// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDMKDYeQ3NbeC1yWoQLMPAqwF-ecExqHw',
    appId: '1:95842404699:web:40555d6df5a890788fb27e',
    messagingSenderId: '95842404699',
    projectId: 'mynotes-yc-flutter-project',
    authDomain: 'mynotes-yc-flutter-project.firebaseapp.com',
    storageBucket: 'mynotes-yc-flutter-project.appspot.com',
    measurementId: 'G-0DCWRNCR73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZdFCdpMP3_IQTYS8-L9omfsqU2L_cCzI',
    appId: '1:95842404699:android:f251f7801b743f0f8fb27e',
    messagingSenderId: '95842404699',
    projectId: 'mynotes-yc-flutter-project',
    storageBucket: 'mynotes-yc-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYyUDyhB7UkbPVw3Y_fMEuygIf9QS3lGw',
    appId: '1:95842404699:ios:c4358a5b4696159f8fb27e',
    messagingSenderId: '95842404699',
    projectId: 'mynotes-yc-flutter-project',
    storageBucket: 'mynotes-yc-flutter-project.appspot.com',
    iosBundleId: 'chaudhary.utkarsh.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYyUDyhB7UkbPVw3Y_fMEuygIf9QS3lGw',
    appId: '1:95842404699:ios:c4358a5b4696159f8fb27e',
    messagingSenderId: '95842404699',
    projectId: 'mynotes-yc-flutter-project',
    storageBucket: 'mynotes-yc-flutter-project.appspot.com',
    iosBundleId: 'chaudhary.utkarsh.mynotes',
  );
}
